### ISSUE TITLE
AppStore Submission

### ISSUE THREAD

**Issue by vilashraj** [Adnuntius/ios_sdk#15]
Can we use Adnuntius for mobile apps? Do we need to take care of anything while submitting the app on AppStore and PlayStore?
Also in iOS we need to use Advertising Identifier, so is Adnuntius using it internally?

**Comment by jason-adnuntius** [comment]
Sorry, Id missed this.    Yes you can use this for submitting apps to the app store.   That is the purpose of the SDK, to give you a library to generate adnuntius ads in your application.

The SDK does not use the advertising identifier but you can pass that to calls to loadAd via the kv or even userId fields.
